//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Pages.Admin.Components
{
    public partial class ContactsPanel
    {
        protected global::System.Web.UI.WebControls.HiddenField hidEditingContactId;
        protected global::System.Web.UI.WebControls.DropDownList ddlPlatform;
        protected global::System.Web.UI.WebControls.TextBox txtContactValue;
        protected global::System.Web.UI.WebControls.TextBox txtContactLabel;
        protected global::System.Web.UI.WebControls.TextBox txtContactUrl;
        protected global::System.Web.UI.WebControls.Button btnAddContact;
        protected global::System.Web.UI.WebControls.Button btnCancelContactEdit;
        protected global::System.Web.UI.WebControls.Repeater rptContactsTable;
    }
}
