//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Pages.Admin.Components
{
    public partial class ProfilePanel
    {
        protected global::System.Web.UI.WebControls.Image imgProfileAvatarThumb;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl profileAvatarSvgPlaceholder;
        protected global::System.Web.UI.WebControls.FileUpload fuProfileAvatar;
        protected global::System.Web.UI.WebControls.HiddenField hidExistingAvatarPath;
        protected global::System.Web.UI.WebControls.TextBox txtProfileFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtProfileLastName;
        protected global::System.Web.UI.WebControls.TextBox txtProfileBirthDate;
        protected global::System.Web.UI.WebControls.Label lblProfileAgeHint;
        protected global::System.Web.UI.WebControls.TextBox txtHeroSubline;
        protected global::System.Web.UI.WebControls.TextBox txtRoleTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroChips;
        protected global::System.Web.UI.WebControls.HiddenField hidHeroNames;
        protected global::System.Web.UI.WebControls.TextBox txtRoleSummary;
        protected global::System.Web.UI.WebControls.TextBox txtFocusArea;
        protected global::System.Web.UI.WebControls.TextBox txtBasedIn;
        protected global::System.Web.UI.WebControls.TextBox txtLocationAddress;
        protected global::System.Web.UI.WebControls.TextBox txtExperienceYears;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
    }
}
