//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio
{
    public partial class AdminMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder adminHead;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder AdminMainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder adminScripts;
    }
}
