//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio
{
    public partial class Admin
    {
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.DashboardPanel ucDashboardPanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.UsersPanel ucUsersPanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.AdminProfilePanel ucAdminProfilePanel;
    }
}
