//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio
{
    public partial class SignIn
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litAlertIcon;
        protected global::System.Web.UI.WebControls.Literal litAlertMsg;
        protected global::System.Web.UI.WebControls.TextBox email;
        protected global::System.Web.UI.WebControls.TextBox password;
        protected global::System.Web.UI.WebControls.CheckBox remember;
        protected global::System.Web.UI.WebControls.Button signInBtn;
        protected global::System.Web.UI.WebControls.TextBox forgotEmail;
        protected global::System.Web.UI.WebControls.TextBox forgotReason;
        protected global::System.Web.UI.WebControls.Button submitForgotReqBtn;
    }
}
