//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Components.Default
{
    public partial class BasicInfoSection
    {
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litLocation;
        protected global::System.Web.UI.WebControls.Literal litAge;
        protected global::System.Web.UI.WebControls.Literal litExperience;
    }
}
