//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Components.Default
{
    public partial class ContactSection
    {
        protected global::System.Web.UI.WebControls.HyperLink contactEmailLink;
        protected global::System.Web.UI.WebControls.Literal litEmailEmpty;
        protected global::System.Web.UI.WebControls.HyperLink contactGithubLink;
        protected global::System.Web.UI.WebControls.Literal litGithubEmpty;
        protected global::System.Web.UI.WebControls.HyperLink contactLinkedinLink;
        protected global::System.Web.UI.WebControls.Literal litLinkedinEmpty;
    }
}
