//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Components.Default
{
    public partial class EducationSection
    {
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl eduList;
        protected global::System.Web.UI.WebControls.Repeater rptEducations;
    }
}
