//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Components.Default
{
    public partial class HeroSection
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl heroDynamicName;
        protected global::System.Web.UI.WebControls.Literal litHeroDynamicName;
        protected global::System.Web.UI.WebControls.Literal litHeroSubline;
        protected global::System.Web.UI.WebControls.Literal litHeroRoleSummary;
        protected global::System.Web.UI.WebControls.Literal litRoleTitle;
        protected global::System.Web.UI.WebControls.Literal litFocusArea;
        protected global::System.Web.UI.WebControls.Literal litBasedIn;
        protected global::System.Web.UI.WebControls.Image imgAvatar;
    }
}
