//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Components.Default
{
    public partial class NavSection
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkNavProfile;
        protected global::System.Web.UI.WebControls.Image imgNavAvatar;
        protected global::System.Web.UI.WebControls.PlaceHolder phNavSvg;
    }
}
