//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Components.Default
{
    public partial class ProjectsSection
    {
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl projectsBento;
        protected global::System.Web.UI.WebControls.Repeater rptProjects;
    }
}
