//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Components.Default
{
    public partial class SkillsSection
    {
        protected global::System.Web.UI.WebControls.Repeater rptSkills;
    }
}
