//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Pages.User.Components
{
    public partial class UserAccountPanel
    {
        protected global::System.Web.UI.WebControls.Literal litUserDisplayName;
        protected global::System.Web.UI.WebControls.TextBox txtUserFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtUserLastName;
        protected global::System.Web.UI.WebControls.TextBox txtUserEmail;
        protected global::System.Web.UI.WebControls.TextBox txtUserNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtUserConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnSaveAccountDetails;
    }
}
