//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio
{
    public partial class AccountProfile
    {
        /// <summary>
        /// imgAvatarPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatarPreview;

        /// <summary>
        /// avatarSvgPlaceholder control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl avatarSvgPlaceholder;


        /// <summary>
        /// litProfileHeaderName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileHeaderName;

        /// <summary>
        /// litStatusText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusText;

        /// <summary>
        /// litMemberSince control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMemberSince;

        /// <summary>
        /// phAdminLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdminLink;

        /// <summary>
        /// pnlAlert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        /// <summary>
        /// litAlertIcon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAlertIcon;

        /// <summary>
        /// litAlertMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAlertMsg;

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRole;

        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// adminQueueSection control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel adminQueueSection;

        /// <summary>
        /// rptAdminRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAdminRequests;

        /// <summary>
        /// btnSaveProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
    }
}
