//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio
{


    public partial class Default
    {

        /// <summary>
        /// NavSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.NavSection NavSectionControl;

        /// <summary>
        /// HeroSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.HeroSection HeroSectionControl;

        /// <summary>
        /// BasicInfoSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.BasicInfoSection BasicInfoSectionControl;

        /// <summary>
        /// TechStackSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.TechStackSection TechStackSectionControl;

        /// <summary>
        /// SkillsSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.SkillsSection SkillsSectionControl;

        /// <summary>
        /// ExperienceSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.ExperienceSection ExperienceSectionControl;

        /// <summary>
        /// ProjectsSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.ProjectsSection ProjectsSectionControl;

        /// <summary>
        /// EducationSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.EducationSection EducationSectionControl;

        /// <summary>
        /// AwardsSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.AwardsSection AwardsSectionControl;

        /// <summary>
        /// HobbiesSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.HobbiesSection HobbiesSectionControl;

        /// <summary>
        /// ContactSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::_24_1639DelMundoPersonalPortfolio.Components.Default.ContactSection ContactSectionControl;
    }
}
