//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24_1639DelMundoPersonalPortfolio.Pages.User
{
    public partial class PortfolioBuilder
    {
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.User.Components.UserAccountPanel ucUserAccountPanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.ProfilePanel ucProfilePanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.TechStackPanel ucTechStackPanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.SkillsPanel ucSkillsPanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.ExperiencePanel ucExperiencePanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.ProjectsPanel ucProjectsPanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.EducationPanel ucEducationPanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.AwardsPanel ucAwardsPanel;
        protected global::_24_1639DelMundoPersonalPortfolio.Pages.Admin.Components.HobbiesPanel ucHobbiesPanel;

        public new _24_1639DelMundoPersonalPortfolio.AdminMaster Master
        {
            get
            {
                return ((_24_1639DelMundoPersonalPortfolio.AdminMaster)(base.Master));
            }
        }
    }
}
